DROP TRIGGER IF EXISTS tg_users_insert_or_update ON users;
DROP TRIGGER IF EXISTS tg_users_delete ON users;
DROP TRIGGER IF EXISTS tg_categories_insert_or_update ON categories;
DROP TRIGGER IF EXISTS tg_categories_delete ON categories;
DROP TRIGGER IF EXISTS tg_warehouse_locations_insert_or_update ON warehouse_locations;
DROP TRIGGER IF EXISTS tg_warehouse_locations_delete ON warehouse_locations;
DROP TRIGGER IF EXISTS tg_containers_insert_or_update ON containers;
DROP TRIGGER IF EXISTS tg_containers_delete ON containers;
DROP TRIGGER IF EXISTS tg_items_insert_or_update ON items;
DROP TRIGGER IF EXISTS tg_items_delete ON items;
DROP TRIGGER IF EXISTS tg_fields_insert_or_update ON fields;
DROP TRIGGER IF EXISTS tg_fields_delete ON fields;
DROP TRIGGER IF EXISTS tg_skus_insert_or_update ON skus;
DROP TRIGGER IF EXISTS tg_skus_delete ON skus;
DROP TRIGGER IF EXISTS tg_stocks_insert_or_update ON stocks;
DROP TRIGGER IF EXISTS tg_stocks_delete ON stocks;
DROP TRIGGER IF EXISTS tg_docking_station_specifications_insert_or_update ON docking_station_specifications;
DROP TRIGGER IF EXISTS tg_docking_station_specifications_delete ON docking_station_specifications;
DROP TRIGGER IF EXISTS tg_graphics_card_specifications_insert_or_update ON graphics_card_specifications;
DROP TRIGGER IF EXISTS tg_graphics_card_specifications_delete ON graphics_card_specifications;
DROP TRIGGER IF EXISTS tg_laptop_specifications_insert_or_update ON laptop_specifications;
DROP TRIGGER IF EXISTS tg_laptop_specifications_delete ON laptop_specifications;
DROP TRIGGER IF EXISTS tg_tft_specifications_insert_or_update ON tft_specifications;
DROP TRIGGER IF EXISTS tg_tft_specifications_delete ON tft_specifications;
DROP TRIGGER IF EXISTS tg_stock_location_history_insert_or_update ON stock_location_history;
DROP TRIGGER IF EXISTS tg_stock_location_history_delete ON stock_location_history;

DROP TRIGGER IF EXISTS tg_item_stock_added ON stocks;
DROP TRIGGER IF EXISTS tg_container_stock_added ON stocks;
DROP TRIGGER IF EXISTS tg_warehouse_location_stock_added ON stocks;
DROP TRIGGER IF EXISTS tg_item_location_updated ON stock_location_history;

DROP FUNCTION IF EXISTS fn_users_notify_event;
DROP FUNCTION IF EXISTS fn_categories_notify_event;
DROP FUNCTION IF EXISTS fn_warehouse_locations_notify_event;
DROP FUNCTION IF EXISTS fn_containers_notify_event;
DROP FUNCTION IF EXISTS fn_items_notify_event;
DROP FUNCTION IF EXISTS fn_fields_notify_event;
DROP FUNCTION IF EXISTS fn_skus_notify_event;
DROP FUNCTION IF EXISTS fn_stocks_notify_event;
DROP FUNCTION IF EXISTS fn_docking_station_specifications_notify_event;
DROP FUNCTION IF EXISTS fn_graphics_card_specifications_notify_event;
DROP FUNCTION IF EXISTS fn_laptop_specifications_notify_event;
DROP FUNCTION IF EXISTS fn_tft_specifications_notify_event;
DROP FUNCTION IF EXISTS fn_stock_location_history_notify_event;
DROP FUNCTION IF EXISTS fn_generate_item_ids;
DROP FUNCTION IF EXISTS fn_delete_item_ids;
DROP FUNCTION IF EXISTS fn_generate_container_ids;
DROP FUNCTION IF EXISTS fn_delete_container_ids;
DROP FUNCTION IF EXISTS fn_item_stock_added;
DROP FUNCTION IF EXISTS fn_container_stock_added;
DROP FUNCTION IF EXISTS fn_warehouse_location_stock_added;
DROP FUNCTION IF EXISTS fn_item_location_updated;
