DROP TRIGGER IF EXISTS tg_users_update ON users;
DROP TRIGGER IF EXISTS tg_categories_update ON categories;
DROP TRIGGER IF EXISTS tg_warehouse_locations_update ON warehouse_locations;
DROP TRIGGER IF EXISTS tg_containers_update ON containers;
DROP TRIGGER IF EXISTS tg_items_update ON items;
DROP TRIGGER IF EXISTS tg_fields_update ON fields;
DROP TRIGGER IF EXISTS tg_skus_update ON skus;
DROP TRIGGER IF EXISTS tg_stocks_update ON stocks;
DROP TRIGGER IF EXISTS tg_docking_station_specifications_update ON docking_station_specifications;
DROP TRIGGER IF EXISTS tg_graphics_card_specifications_update ON graphics_card_specifications;
DROP TRIGGER IF EXISTS tg_laptop_specifications_update ON laptop_specifications;
DROP TRIGGER IF EXISTS tg_tft_specifications_update ON tft_specifications;
DROP TRIGGER IF EXISTS tg_stock_location_history_update ON stock_location_history;
DROP TRIGGER IF EXISTS tg_item_stock_added ON stocks;
DROP TRIGGER IF EXISTS tg_container_stock_added ON stocks;
DROP TRIGGER IF EXISTS tg_warehouse_location_stock_added ON stocks;
DROP TRIGGER IF EXISTS tg_item_location_updated ON stock_location_history;

DROP FUNCTION IF EXISTS fn_users_notify_event;
DROP FUNCTION IF EXISTS fn_categories_notify_event;
DROP FUNCTION IF EXISTS fn_warehouse_locations_notify_event;
DROP FUNCTION IF EXISTS fn_containers_notify_event;
DROP FUNCTION IF EXISTS fn_items_notify_event;
DROP FUNCTION IF EXISTS fn_fields_notify_event;
DROP FUNCTION IF EXISTS fn_skus_notify_event;
DROP FUNCTION IF EXISTS fn_stocks_notify_event;
DROP FUNCTION IF EXISTS fn_docking_station_specifications_notify_event;
DROP FUNCTION IF EXISTS fn_graphics_card_specifications_notify_event;
DROP FUNCTION IF EXISTS fn_laptop_specifications_notify_event;
DROP FUNCTION IF EXISTS fn_tft_specifications_notify_event;
DROP FUNCTION IF EXISTS fn_stock_location_history_notify_event;
DROP FUNCTION IF EXISTS fn_generate_item_ids;
DROP FUNCTION IF EXISTS fn_delete_item_ids;
DROP FUNCTION IF EXISTS fn_generate_container_ids;
DROP FUNCTION IF EXISTS fn_delete_container_ids;
DROP FUNCTION IF EXISTS fn_item_stock_added;
DROP FUNCTION IF EXISTS fn_container_stock_added;
DROP FUNCTION IF EXISTS fn_warehouse_location_stock_added;
DROP FUNCTION IF EXISTS fn_item_location_updated;
