DROP TRIGGER IF EXISTS users_update_trigger ON users;
DROP TRIGGER IF EXISTS tg_users_update_trigger ON users;
DROP TRIGGER IF EXISTS categories_update_trigger  ON categories;
DROP TRIGGER IF EXISTS tg_categories_update_trigger   ON categories;
DROP TRIGGER IF EXISTS warehouse_locations_update_trigger ON warehouse_locations;
DROP TRIGGER IF EXISTS tg_warehouse_locations_update_trigger ON warehouse_locations;
DROP TRIGGER IF EXISTS containers_update_trigger ON containers;
DROP TRIGGER IF EXISTS tg_containers_update_trigger ON containers;
DROP TRIGGER IF EXISTS items_update_trigger ON items;
DROP TRIGGER IF EXISTS tg_items_update_trigger ON items;
DROP TRIGGER IF EXISTS fields_update_trigger ON fields;
DROP TRIGGER IF EXISTS tg_fields_update_trigger ON fields;
DROP TRIGGER IF EXISTS skus_update_trigger ON skus;
DROP TRIGGER IF EXISTS tg_skus_update_trigger ON skus;
DROP TRIGGER IF EXISTS stocks_update_trigger ON stocks;
DROP TRIGGER IF EXISTS tg_stocks_update_trigger ON stocks;
DROP TRIGGER IF EXISTS stock_location_history_update_trigger ON stock_location_history;
DROP TRIGGER IF EXISTS tg_stock_location_history_update_trigger ON stock_location_history;
DROP TRIGGER IF EXISTS docking_station_specifications_update_trigger ON docking_station_specifications;
DROP TRIGGER IF EXISTS tg_docking_station_specifications_update_trigger ON docking_station_specifications;
DROP TRIGGER IF EXISTS laptop_specifications_update_trigger ON laptop_specifications;
DROP TRIGGER IF EXISTS tg_laptop_specifications_update_trigger On laptop_specifications;
DROP TRIGGER IF EXISTS tft_specifications_update_trigger ON tft_specifications;
DROP TRIGGER IF EXISTS tg_tft_specifications_update_trigger ON tft_specifications;

DROP FUNCTION IF EXISTS categories_notify_event;
DROP FUNCTION IF EXISTS containers_notify_event;
DROP FUNCTION IF EXISTS docking_station_specifications_notify_event;
DROP FUNCTION IF EXISTS fields_notify_event;
DROP FUNCTION IF EXISTS fn_categories_notify_event;
DROP FUNCTION IF EXISTS fn_containers_notify_event;
DROP FUNCTION IF EXISTS fn_docking_station_specifications_notify_event;
DROP FUNCTION IF EXISTS fn_fields_notify_event;
DROP FUNCTION IF EXISTS fn_items_notify_event;
DROP FUNCTION IF EXISTS fn_laptop_specifications_notify_event;
DROP FUNCTION IF EXISTS fn_skus_notify_event;
DROP FUNCTION IF EXISTS fn_stock_location_history_notify_event;
DROP FUNCTION IF EXISTS fn_stocks_notify_event;
DROP FUNCTION IF EXISTS fn_tft_specifications_notify_event;
DROP FUNCTION IF EXISTS fn_users_notify_event;
DROP FUNCTION IF EXISTS fn_warehouse_locations_notify_event;
DROP FUNCTION IF EXISTS items_notify_event;
DROP FUNCTION IF EXISTS laptop_specifications_notify_event;
DROP FUNCTION IF EXISTS skus_notify_event;
DROP FUNCTION IF EXISTS stock_location_history_notify_event;
DROP FUNCTION IF EXISTS stocks_notify_event;
DROP FUNCTION IF EXISTS tft_specifications_notify_event;
DROP FUNCTION IF EXISTS users_notify_event;
DROP FUNCTION IF EXISTS warehouse_locations_notify_event;
